// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://cjasisdwnefvymhcidgm.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqYXNpc2R3bmVmdnltaGNpZGdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI2ODk0MTgsImV4cCI6MjA0ODI2NTQxOH0.zGtYbgYAajthpS_0la1Dn-aQXsHH45Pn9BfWBui-_9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);